spring.application.name=agent
logging.level.org.springframework.ai=DEBUG
spring.ai.bedrock.converse.chat.options.model=global.anthropic.claude-sonnet-4-20250514-v1:0
spring.ai.bedrock.converse.chat.options.max-tokens=4096

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.datasource.url=jdbc:postgresql://workshop-db-cluster.cluster-cvai6ugqwo2n.us-east-1.rds.amazonaws.com:5432/workshop